baseURL = "/"
languageCode = "en-US"
title = "Bijan Camp | Software Engineer | Azure Data & AI"
# Enable comments by entering your Disqus shortname
disqusShortname = "bijancamp"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hyde"

[params]
  avatar = "/images/profile.png"
  author = "Bijan Camp"
  headline = "Software Engineer | Azure Data & AI"
  description = "Software Engineering Blog"
  publicURL = "http://bijancamp.com/"

  themeColor = "theme-base-0d"

## Main Menu
[[menu.main]]
  name = "About"
  identifier = "about"
  weight = 100
  url = "/about/"
[[menu.main]]
  name = "Projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "Posts"
  identifier = "posts"
  weight = 300
  url = "/blog/"
[[menu.main]]
  name = "Medium"
  identifier = "medium"
  weight = 400
  url = "https://medium.com/@bijancamp"
[[menu.main]]
  name = "Linkedin"
  identifier = "linkedin"
  weight = 500
  url = "https://linkedin.com/in/bijancamp"
