baseURL = "/"
languageCode = "en-US"
title = "Bijan Camp | Data Consultant"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "images/profile.png"
  author = "Bijan Camp"
  description = "Personal website for Bijan Camp"

  # Custom assets can be linked with their paths relative to static/
  custom_css = ["css/main.css"]
  custom_js  = []

[params.social]
  Github        = "bijancamp"
  Email         = "hello@bijancamp.com"
  Twitter       = "bijancamp"
  LinkedIn      = "bijancamp"
  Medium        = "bijancamp"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "https://medium.com/@bijancamp"
[[menu.main]]
  name = "github"
  identifier = "github"
  weight = 200
  url = "https://github.com/bijancamp"
[[menu.main]]
  name = "linkedin"
  identifier = "linkedin"
  weight = 300
  url = "https://linkedin.com/in/bijancamp"
